export type Customer = {
  id: number;
  name: string;
  avatar: string;
  email: string;
  phone: string;
  address: string;
  joined: string;
  orders: number;
  totalSpend: number;
  lastOrder: string;
  status: "Active" | "Inactive";
};

export const customersData: Customer[] = [
  {
    id: 1,
    name: "John Doe",
    avatar: "https://i.pravatar.cc/100?img=1",
    email: "john@example.com",
    phone: "+1 555-1234",
    address: "123 Main St, NY",
    joined: "2024-03-01",
    orders: 5,
    totalSpend: 325.75,
    lastOrder: "2024-07-10",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    avatar: "https://i.pravatar.cc/100?img=2",
    email: "jane@example.com",
    phone: "+1 555-5678",
    address: "456 Elm St, CA",
    joined: "2024-04-15",
    orders: 2,
    totalSpend: 89.99,
    lastOrder: "2024-06-15",
    status: "Active",
  },
  {
    id: 3,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 5,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 9,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 10,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Mark Johnson",
    avatar: "https://i.pravatar.cc/100?img=3",
    email: "mark@example.com",
    phone: "+1 555-9999",
    address: "789 Pine St, IL",
    joined: "2024-01-12",
    orders: 0,
    totalSpend: 0,
    lastOrder: "-",
    status: "Inactive",
  },
];
